feat: main screen markup
worldcoin/simulator pull request #142
Opened 2023-05-10 09:10 UTC by michaelfurutin

2023-05-10 19:40 UTC, igorosip0v requested changes

2023-05-10 19:40 UTC, igorosip0v commented on src/pages/id/[id]/Scanner/index.tsx
> +import React from "react";
@michaelfurutin  This file causing the build to fail.

2023-05-10 19:40 UTC, igorosip0v commented on src/pages/id/[id]/Settings/index.tsx
> +import React from "react";
@michaelfurutin  This file causing the build to fail.

2023-05-10 22:13 UTC, igorosip0v approved these changes

2023-05-11 20:53 UTC, maxpetretta approved these changes

2023-05-11 20:53 UTC, merged