refactor: replace walletconnect with bridge
worldcoin/simulator pull request #188
Opened 2023-11-28 21:56 UTC by igorosip0v

2023-11-29 21:45 UTC, 0xPenryn requested changes

2023-11-29 21:45 UTC, 0xPenryn commented on package.json
> +    "@worldcoin/idkit-core": "1.0.0-alpha.0",
once 1.0.0-alpha.1 is published we'll need to update this, but other than that this PR is good to go

2023-11-29 21:45 UTC, 0xPenryn commented on src/lib/proof.ts
why doesn't this get an inclusion proof from the sequencer any longer? if we just generate a group and insert the single identity then proofs will never actually verify at all

2023-11-30 15:37 UTC, igorosip0v commented on package.json
> +    "@worldcoin/idkit-core": "1.0.0-alpha.0",
Sure!

2023-11-30 20:58 UTC, 0xPenryn approved these changes
should merge to a staging branch if possible rather than main, for the time being

2023-12-06 14:08 UTC, merged