Dev
worldcoin/simulator pull request #189
Opened 2023-12-06 14:09 UTC by igorosip0v

Closes [WID-525](https://linear.app/worldcoin/issue/WID-525/world-id-bridge-is-implemented-in-simulator)

### What is done: 
- Removed walletconnect related code/packages
- Added endpoints/helpers for bridge support.
- Minor improvement

### Known issues
- ~`PUT {bridge_url}/response/{request_id}` returns `405 Method Not Allowed` ❗❗❗~
  - Resolved 
- ~`@worldcoin/idkit-core` still have issue with the extensions~
  - ~This is why test and build is broken~
  - Resolved

- ~Still using `idkit` 0.5.1 to generate external_nullifer~
  - Resolved

### Diagram

```mermaid
flowchart TD
    A[User opens Simulator] --> B[Press scan button];
    B --> C[Choose between scan and manual input];
    C --> D[Scanner recognizes url];
    D --> E[passing url to performVerification]
    E --> F["/api/pair-client"]
    F --> G["Getting data from 'GET {bridgeURL}/request/${requestUUID}'"]
    G --> H["return `{app_id,credential_type,action_description,action,signal}`"]
    H --> H1{Success?}
    H1 -->|no| If["reset process"]
    If --> If1["Show error"]
    H1 -->|yes| Is["Saving URL to store"]
    Is --> Is1["Generating fullProof"]
    Is1 --> J1["Receiving metadata from {dev_portal}/api/v1/precheck"]
    J1 --> J2["Saving metadata to storage"]
    J2 --> K["Showing modal with received metadata, credentials options and verify button"]
    K --> L["User selects credentials and press verify"]
    L --> M["/api/approve-request"]
    M --> N["validating + formatting payload + encrypt payload"]
    N --> O["PUT {bridgeURL}/request/${requestUUID}"]
    O --> P{Success?}
    P -->|yes| Ps["???"]
    P -->|no| Pf[???] 
```

2023-12-09 16:02 UTC, pdtfh commented
Pushed changes:
- Fix merge conflicts related to the update of SnarkJS
- We were previously sending the `nullifier_hash` to the Dev Portal's precheck endpoint as a stringified BigInt, which means we would have always gotten incorrect values for `can_user_verify`
- We no longer need to send `external_nullifier` to the precheck endpoint

2023-12-09 16:05 UTC, pdtfh commented on src/components/Modal/index.tsx
> +        const res = await fetch("/api/approve-request", {
why is this an API request, seems best to handle client-side to better simulate how the mobile apps work

2023-12-09 16:06 UTC, pdtfh commented on src/types/common.ts
> +export { CredentialType } from "@worldcoin/idkit-core";
worth removing the export to avoid confusion

2023-12-09 16:07 UTC, pdtfh commented on src/pages/api/pair-client/index.ts
> +import { errorResponse } from "@/helpers/error-response";
same as above, let's keep this client side

2023-12-09 18:32 UTC, igorosip0v commented on src/components/Modal/index.tsx
> +        const res = await fetch("/api/approve-request", {
Because we are using some things that are available by default only on the server side (Buffer for example). Also, I am not sure how the way the web client side works is close to mobile.

2023-12-09 18:50 UTC, igorosip0v commented on src/types/common.ts
> +export { CredentialType } from "@worldcoin/idkit-core";
Done

2023-12-10 12:36 UTC, 0xPenryn requested changes
if i paste in a URL that's a valid format but doesn't have an active bridge session (such as accidentally pasting the same URL after already doing a verification, or changing a single character in the UUID), i end up being shown the environment error "cannot verify production app on simulator"

we should probably create a modal state reflecting an error if we're unable to pair with the bridge or an invalid/empty payload is returned

2023-12-11 00:40 UTC, igorosip0v commented on src/components/Modal/index.tsx
> -                  metadata.verified_app_logo ||
@0xPenryn I assume it can be an empty string. In this case `||` will work.

2023-12-11 00:46 UTC, igorosip0v commented on src/components/Modal/index.tsx
> -                  metadata.verified_app_logo ||
Just tested

<img width="236" alt="image" src="https://github.com/worldcoin/simulator/assets/89008845/8316b3e5-8f67-4d6c-813e-d9c041ffd3e0">

2023-12-11 00:46 UTC, igorosip0v commented on src/components/Modal/index.tsx
> +        const res = await fetch("/api/approve-request", {
#192

2023-12-11 00:46 UTC, igorosip0v commented on src/pages/api/pair-client/index.ts
> +import { errorResponse } from "@/helpers/error-response";
#192

2023-12-11 18:16 UTC, pdtfh approved these changes

2023-12-11 18:28 UTC, merged