Simulator UX update for easier copying and submitting false proofs.
worldcoin/simulator pull request #198
Opened 2023-12-13 15:55 UTC by andy-t-wang

2023-12-13 18:22 UTC, andy-t-wang commented
https://github.com/worldcoin/simulator/assets/41224501/6cce7d78-1805-4c4b-8db8-710e68fad95a


https://github.com/worldcoin/simulator/assets/41224501/15dcdc6a-ca64-4962-a924-05ac7ffedc8c

Videos for the update

2023-12-13 18:24 UTC, andy-t-wang commented
Changes: 
1. Auto selects the highest level of verification available on simulator user (remove selection screen)
2. Update verification UI to match more closely with current App UX
3. Generate a valid proof for a fake identity tree to test malicious users via the verifyProof endpoint
4. Split out the QR code and the paste screen for more visual clarity.

2023-12-14 15:41 UTC, pdtfh commented on src/components/Modal/ModalStatus.tsx
> +            <span className="ml-3">Approve with World ID</span>
```suggestion
            <span className="ml-3">Verify with World ID</span>
```

source: https://docs.worldcoin.org/id/verify-with-world-id

2023-12-14 15:42 UTC, pdtfh commented on src/components/QR/QRScanner.tsx
> -            onClick={onClickManualInput}
don't feel very strong about this, but we could keep it for ease?

2023-12-14 15:46 UTC, pdtfh commented on src/lib/proof.ts
> +  console.warn("Identity inclusion proof was not found, using dummy proof");
in a follow up PR, but instead of doing this let's error similar to World App ([design](https://www.figma.com/file/56IXS8QdsaJLzbcXkPrY8x/%F0%9F%92%8E-World-App-Handoff-(2.0)?type=design&node-id=37950%3A98677&mode=design&t=jEXPATq9fzus5sez-1))

2023-12-14 15:53 UTC, pdtfh requested changes
great stuff @andy-t-wang! significant UX improvements, suggestions inline

2023-12-14 15:53 UTC, pdtfh commented on src/lib/proof.ts
> +  malicious?: boolean,
let's drop this, it can be confusing, we can just use the simulated inclusion proofs for the error case

2023-12-14 15:53 UTC, pdtfh commented on src/components/Modal/index.tsx
> +const DynamicWorldID = dynamic(() => import("@/components/WorldID"), {
why do we need dynamic imports for this component? this has usually hidden problems in the past

2023-12-14 15:53 UTC, pdtfh commented on src/components/Modal/index.tsx
> +  const biometricsChecked = useMemo(() => {
this logic can be simplified, instead of having these states, just have a very simple method that performs the credential selection when relevant

2023-12-14 15:53 UTC, pdtfh commented on src/components/Modal/index.tsx
> +              Test Malicious Proof
```suggestion
              Test Invalid Proof
```

2023-12-14 15:53 UTC, pdtfh commented on src/components/Modal/index.tsx
> +                {metadata.name ?? "App Name"} is asking for permission to your
" is asking for permission to verify you with your World ID."

2023-12-16 07:10 UTC, pdtfh commented on src/lib/proof.ts
> +export const getDummyFullProof = async (
duplicated code logic here, perhaps best to refactor getFullProof to avoid it

2023-12-16 07:11 UTC, pdtfh commented on src/components/Modal/index.tsx
> +              className="mb-4 font-bold text-error-700"
let's make this gray instead or lighter red, otherwise the button can draw too much attention

2023-12-16 07:11 UTC, pdtfh approved these changes

2023-12-17 17:28 UTC, andy-t-wang commented on src/components/Modal/index.tsx
> +              className="mb-4 font-bold text-error-700"
![Uploading Screenshot 2023-12-17 at 9.28.17 AM.png…]()

2023-12-17 17:54 UTC, andy-t-wang commented on src/components/Modal/index.tsx
> +              className="mb-4 font-bold text-error-700"
<img width="363" alt="Screenshot 2023-12-17 at 9 54 30 AM" src="https://github.com/worldcoin/simulator/assets/41224501/196cc016-6b41-4f5e-ab20-0da2108d558c">

2023-12-17 17:54 UTC, andy-t-wang commented on src/lib/proof.ts
> +export const getDummyFullProof = async (
Refactored into merkle root being passed in

2023-12-18 17:04 UTC, merged